INSERT INTO tipodocidentidad (nombre,abrev,descripcion,nrocaracteres,enabled) VALUES ('DOCUMENTO NACIONAL DE IDENTIDAD','D.N.I.',NULL,8,1);

INSERT INTO procedenciapersona (nombre,enabled) VALUES ('CIVIL',1);
INSERT INTO procedenciapersona (nombre,enabled) VALUES ('POLICIAL',1);
INSERT INTO procedenciapersona (nombre,enabled) VALUES ('CIVIL (EX PNP)',1);

INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0003','GRAL. DE POLICÍA','GENERAL DE POLICÍA',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0010','TNTE. GRAL.','TENIENTE GENERAL',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0020','GRAL.','GENERAL',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0030','CRNL.','CORONEL',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0040','CMDTE.','COMANDANTE',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0050','MAY.','MAYOR',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0060','CAP.','CAPITAN',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0070','TNTE.','TENIENTE',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0080','ALFZ.','ALFEREZ',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0022','GRAL. S','GENERAL',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0032','CRNL. S','CORONEL S',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0042','CMDTE. S','COMANDANTE S',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0052','MAY. S','MAYOR S',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0053','MAY. S ASIMILADO','MAYOR S ASIMILADO',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0062','CAP. S','CAPITAN S',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0064','CAP.S ASIMILADO','CAPITAN S ASIMILADO',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0072','TNTE. S','TENIENTE S',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0074','TNTE. A','TENIENTE A',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0082','ALFZ. S','ALFEREZ S',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0084','ALFZ. A','ALFEREZ A',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0034','CRNL. MA','CORONEL MA',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0044','CMDTE. MA','COMANDANTE MA',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0054','MAY. MA','MAYOR MA',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0066','CAP. MA','CAPITAN MA',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0076','TNTE. MA','TENIENTE MA',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0086','ALFZ. MA','ALFEREZ MA',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0110','SS','SUB OFICIAL SUPERIOR',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0120','SB','SUB OFICIAL BRIGADIER',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0130','ST1','SUB OFICIAL TECNICO 1RA',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0140','ST2','SUB OFICIAL TECNICO 2DA',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0150','ST3','SUB OFICIAL TECNICO 3RA',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0160','S1','SUB OFICIAL 1RA',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0170','S2','SUB OFICIAL 2DA',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0180','S3 ','SUB OFICIAL 3RA',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0112','SS S','SUB OFICIAL SUPERIOR S',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0122','SB S','SUB OFICIAL BRIGADIER S',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0132','ST1 S','SUB OFICIAL TECNICO 1RA S',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0142','ST2 S','SUB OFICIAL TECNICO 2DA S',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0152','ST3 S','SUB OFICIAL TECNICO 3RA S',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0162','S1 S','SUB OFICIAL 1RA S',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0172','S2 S','SUB OFICIAL 2DA S',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0182','S3 S','SUB OFICIAL 3RA S',1);
INSERT INTO grado (id,abrev,nombre,enabled) VALUES ('0184','S3 S ASIMILADO','SUB OFICIAL 3RA S ASIMILADO',1);

INSERT INTO persona (tipodocidentidad_id,nrodocidentidad,nombre,apepat,apemat,cip,fecnac,direccion,create_at,grado_id,unidadpnp_id,procedenciapersona_id) VALUES (1,'43795932','LUIS RICARDO','LLAMPAZO','MANDAMIENTO','00391305','20/09/1986',NULL,'11/05/2020','0062',NULL,2);

INSERT INTO usuario (username,password,enabled,conected) VALUES ('00391305','$2a$10$O9wxmH/AeyZZzIS09Wp8YOEMvFnbRVJ8B4dmAMVSGloR62lj.yqXG',1,0);

INSERT INTO role (authority,nombre) VALUES ('ROLE_ADMIN','Administrador');
INSERT INTO role (authority,nombre) VALUES ('ROLE_IG','Inspector General');
INSERT INTO role (authority,nombre) VALUES ('ROLE_DIRINV','Direccion de Investigaciones');
INSERT INTO role (authority,nombre) VALUES ('ROLE_INVDIR','Director DIRINV');
INSERT INTO role (authority,nombre) VALUES ('ROLE_INVUTD','Trámite Documentario DIRINV');
INSERT INTO role (authority,nombre) VALUES ('ROLE_OD','Oficina de Disciplina');
INSERT INTO role (authority,nombre) VALUES ('ROLE_JEFOD','Jefatura');
INSERT INTO role (authority,nombre) VALUES ('ROLE_SECOD','Secretaría');
INSERT INTO role (authority,nombre) VALUES ('ROLE_INSTOD','Instructor');
INSERT INTO role (authority,nombre) VALUES ('ROLE_AUXOD','Auxiliar');
INSERT INTO role (authority,nombre) VALUES ('ROLE_ODT','OD Turno');
INSERT INTO role (authority,nombre) VALUES ('ROLE_CEOPOL','CEOPOL');
INSERT INTO role (authority,nombre) VALUES ('ROLE_UTDIG','Tramite Documentario IGPNP');

INSERT INTO authorities (usuario_id,role_id) VALUES (1,6);
INSERT INTO authorities (usuario_id,role_id) VALUES (1,7);

INSERT INTO cargo (nombre,enabled) VALUES ('AUXILIAR',1);

INSERT INTO tipounidadinspectoria (nombre,enabled) VALUES ('ADMINISTRATIVO',1);
INSERT INTO tipounidadinspectoria (nombre,enabled) VALUES ('INVESTIGACION',1);
INSERT INTO tipounidadinspectoria (nombre,enabled) VALUES ('DESICIÓN',1);
INSERT INTO tipounidadinspectoria (nombre,enabled) VALUES ('SEGUNDA INSTANCIA',1);
INSERT INTO tipounidadinspectoria (nombre,enabled) VALUES ('INSPECCCIONES',1);
INSERT INTO tipounidadinspectoria (nombre,enabled) VALUES ('CONTROL Y SUPERVISION',1);


INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORÍA GENERAL','IGPNP',NULL,'IG-PNP',0,1,NULL,0,0);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('SECRETARIA','SEC','ARAMBURU','SEC/IG-PNP',1,1,1,0,0);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('DIVISION DE INTELIGENCIA DE INSPECTORIA GENERAL','DIVIN','ARAMBURU','DIVIN/IG-PNP',1,1,1,0,0);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('DIRECCION DE INVESTIGACIONES','DIRINV','ARAMBURU','DIRINV/IG-PNP',1,1,1,1,0);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('DIRECCION DE INSPECCIONES','DIRINS','ARAMBURU','DIRINS/IG-PNP',1,1,1,1,0);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('UNIDAD DE TRAMITE DOCUMENTARIO','UTD','ARAMBURU','UTD',2,1,2,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('UNIDAD DE ARCHIVO E INFORMACION','UAI','ARAMBURU','UAI',2,1,2,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('UNIDAD DE TECNOLOGIA DE LA INFORMACION Y COMUNICACIONES','UNITIC','ARAMBURU','UNITIC',2,1,2,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('UNIDAD DE SEGURIDAD DE INSTALACIONES','UNISEINS','ARAMBURU','UNISEINS',2,1,2,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('UNIDAD DE ASESORIA JURIDICA','UNIASJUR','ARAMBURU','UNIASJUR',2,1,2,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('UNIDAD DE PLANEAMIENTO Y EDUCACION','UNIPLEDU','ARAMBURU','UNIPLEDU',2,1,2,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE ADMINISTRACION','OFIAD','ARAMBURU','OFIAD',2,1,2,0,0);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('JEFATURA DE ORDENES','JEFORD','ARAMBURU','JEFORD',2,1,2,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('UNIDAD DE COMUNICACION E IMAGEN INSTITUCIONAL','UNICI','ARAMBURU','UNICI',2,1,2,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('UNIDAD DE LUCHA CONTRA LA CORRUPCION','UNILCC','ARAMBURU','UNILCC',2,1,2,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('UNIDAD DE EVALUACION Y FISCALIZACION POSTERIOR DE EXPEDIENTES ADMINISTRATIVOS DISCIPLINARIOS','UNIEFPEAD','ARAMBURU','UNIEFPEAD',2,1,2,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('UNIDAD DE EVALUACION DE INVESTIGACIONES EXTRAORDINARIAS','UNIEIE','ARAMBURU','UNIEIE',2,1,2,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('AYUDANTIA','AYU','ARAMBURU','AYU',2,1,2,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('DEPARTAMENTO DE BUSQUEDA','DEPBUS','ARAMBURU','DEPBUS',2,1,3,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('DEPARTAMENTO DE ANALISIS','DEPANA','ARAMBURU','DEPANA',2,1,3,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('DEPARTAMENTO DE CONTRAINTELIGENCIA','DEPCI','ARAMBURU','DEPCI',2,1,3,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('DEPARTAMENTO DE SEGURIDAD DIGITAL','DEPSD','ARAMBURU','DEPSD',2,1,3,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('DIRECCION','DIR','ARAMBURU','DIR',2,1,4,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('SECRETARIA','SEC','ARAMBURU','SEC',2,1,4,0,0);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINAS DE DISCIPLINA','OD','ARAMBURU','OD',2,1,4,1,0);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIAS DESCENTRALIZADAS','ID','ARAMBURU','ID',2,1,4,1,0);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIAS MACRO REGIONALES','IMR','ARAMBURU','IMR',2,1,4,1,0);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('DIRECCION','DIR','ARAMBURU','DIR',2,1,5,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('SECRETARIA','SEC','ARAMBURU','SEC',2,1,5,0,0);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('DIVISION DE INSPECCIONES','DIVINS','ARAMBURU','DIVINS',2,1,5,0,0);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('DIVISION DE CONTROL Y SUPERVISION DE LOS SERVICIOS POLICIALES','DIVCSPAD','ARAMBURU','DIVCSPAD',2,1,5,0,0);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('AREA DE RECURSOS HUMANOS','AREHUM','ARAMBURU','AREHUM',3,1,12,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('AREA DE LOGISTICA','ARELOG','ARAMBURU','ARELOG',3,1,12,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('AREA DE BIENESTAR Y APOYO AL POLICIA','AREBAP','ARAMBURU','AREBAP',3,1,12,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE ADMINISTRACION','OFAD','ARAMBURU','OFAD',3,1,24,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('UNIDAD DE TECNOLOGIA DE LA INFORMACION Y COMUNICACIONES','UNITIC','ARAMBURU','UNITIC',3,1,24,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('UNIDAD DE MONITOREO, EVALUACION Y FISCALIZACION DE INVESTIGACIONES ADMINISTRATIVAS DISCIPLINARIAS','UMEFIAD','ARAMBURU','UMEFIAD',3,1,24,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('JEFATURA DE ORDENES','JEFORD','ARAMBURU','JEFORD',3,1,24,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('UNIDAD DE ASESORIA JURIDICA','UNIASJUR','ARAMBURU','UNIASJUR',3,1,24,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('UNIDAD DE TRAMITE DOCUMENTARIO','UTD','ARAMBURU','UTD',3,1,24,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('AYUDANTIA','AYU','ARAMBURU','AYU',3,1,24,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 01 - LIMA CALLAO (ARAMBURU)','OD Nº 01','ARAMBURU','OD Nº 01',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 02 - LIMA CALLAO (ARAMBURU)','OD Nº 02','ARAMBURU','OD Nº 02',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 03 - LIMA CALLAO (DIRECCION CONTRA EL TERRORISMO)','OD Nº 03','DIRECCION CONTRA EL TERRORISMO','OD Nº 03',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 04 - LIMA CALLAO (DIRECCION DE INVESTIGACION CRIMINAL)','ODNº 04','DIRECCION DE INVESTIGACION CRIMINAL','ODNº 04',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 05 - LIMA CALLAO (ESCUELA NACIONAL DE FORMACION PROFESIONAL POLICIAL)','OD Nº 05','ESCUELA NACIONAL DE FORMACION PROFESIONAL POLICIAL','OD Nº 05',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 06 - LIMA CALLAO (DIRECCION DE ADMINISTRACION)','OD Nº 06','DIRECCION DE ADMINISTRACION','OD Nº 06',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 07 - LIMA CALLAO (DIRECCION DE RECURSOS HUMANOS)','OD Nº 07','DIRECCION DE RECURSOS HUMANOS','OD Nº 07',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 08 - LIMA CALLAO (DIRECCION DE BIENESTAR Y APOYO AL POLICIA)','OD Nº 08','DIRECCION DE BIENESTAR Y APOYO AL POLICIA','OD Nº 08',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 09 - LIMA CALLAO (DIRECCION DE CRIMINALISTICA)','OD Nº 09','DIRECCION DE CRIMINALISTICA','OD Nº 09',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 10 - LIMA CALLAO (DIRECCION DE SANIDAD POLICIAL)','OD Nº 10','DIRECCION DE SANIDAD POLICIAL','OD Nº 10',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 11 - LIMA CALLAO (DIRECCION ANTIDROGAS)','OD Nº 11','DIRECCION ANTIDROGAS','OD Nº 11',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 12 - LIMA CALLAO (DIRECCION DE OPERACIONES ESPECIALES)','OD Nº 12','DIRECCION DE OPERACIONES ESPECIALES','OD Nº 12',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 13 - LIMA CALLAO (DIRECCION DE SEGURIDAD INTEGRAL)','OD Nº 13','DIRECCION DE SEGURIDAD INTEGRAL','OD Nº 13',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 14 - LIMA CALLAO (DIRECCION DE TRANSITO, TRANSPORTE Y SEGURIDAD VIAL)','OD Nº 14','DIRECCION DE TRANSITO, TRANSPORTE Y SEGURIDAD VIAL','OD Nº 14',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 15 - LIMA CALLAO (CALLAO)','OD Nº 15','CALLAO','OD Nº 15',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 16 - LIMA PROVINCIAS (CHOSICA)','OD Nº 16','CHOSICA','OD Nº 16',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 17 - LIMA PROVINCIAS (CAÑETE)','OD Nº 17','CAÑETE','OD Nº 17',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 18 - LIMA PROVINCIAS (HUACHO)','OD Nº 18','HUACHO','OD Nº 18',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 01 ASUNTOS ESPECIALES A NIVEL NACIONAL (ARAMBURU)','OD Nº 01 AE','ARAMBURU','OD Nº 01 AE',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 02 ASUNTOS ESPECIALES A NIVEL NACIONAL (ARAMBURU)','OD Nº 02 AE','ARAMBURU','OD Nº 02 AE',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 03 ASUNTOS ESPECIALES A NIVEL NACIONAL (ARAMBURU)','OD Nº 03 AE','ARAMBURU','OD Nº 03 AE',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 04 ASUNTOS ESPECIALES LA LIBERTAD (TRUJILLO)','OD Nº 04 AE','TRUJILLO','OD Nº 04 AE',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA Nº 05 ASUNTOS ESPECIALES AREQUIPA (AREQUIPA)','OD Nº 05 AE','AREQUIPA','OD Nº 05 AE',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA AMAZONAS (CHACHAPOYAS)','OD AMAZONAS','CHACHAPOYAS','OD AMAZONAS',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA ANCASH (CHIMBOTE)','OD ANCASH','CHIMBOTE','OD ANCASH',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA ANCASH (HUARAZ)','OD ANCASH','HUARAZ','OD ANCASH',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA APURIMAC (ABANCAY)','OD APURIMAC','ABANCAY','OD APURIMAC',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA AREQUIPA (AREQUIPA)','OD AREQUIPA','AREQUIPA','OD AREQUIPA',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA AREQUIPA (CAMANA)','OD AREQUIPA','CAMANA','OD AREQUIPA',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA CAJAMARCA (CAJAMARCA)','OD CAJAMARCA','CAJAMARCA','OD CAJAMARCA',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA CAJAMARCA (JAEN)','OD CAJAMARCA','JAEN','OD CAJAMARCA',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA CUSCO (CUSCO)','OD CUSCO','CUSCO','OD CUSCO',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA FP VRAEM (HUANTA)','OD FP VRAEM','HUANTA','OD FP VRAEM',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA HUANCAVELICA (HUANCAVELICA)','OD HUANCAVELICA','HUANCAVELICA','OD HUANCAVELICA',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA HUANUCO (HUANUCO)','OD HUANUCO','HUANUCO','OD HUANUCO',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA HUANUCO (TINGO MARIA)','OD HUANUCO','TINGO MARIA','OD HUANUCO',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA ICA (ICA)','OD ICA','ICA','OD ICA',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA JUNIN (HUANCAYO)','OD JUNIN','HUANCAYO','OD JUNIN',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA JUNIN (LA MERCED)','OD JUNIN','LA MERCED','OD JUNIN',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA LA LIBERTAD (TRUJILLO)','OD LA LIBERTAD','TRUJILLO','OD LA LIBERTAD',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA LAMBAYEQUE (CHICLAYO)','OD LAMBAYEQUE','CHICLAYO','OD LAMBAYEQUE',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA LORETO (IQUITOS)','OD LORETO','IQUITOS','OD LORETO',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA MADRE DE DIOS (PUERTO MALDONADO)','OD MADRE DE DIOS','PUERTO MALDONADO','OD MADRE DE DIOS',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA MOQUEGUA (MOQUEGUA)','OD MOQUEGUA','MOQUEGUA','OD MOQUEGUA',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA PIURA (PIURA)','OD PIURA','PIURA','OD PIURA',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA PIURA (SULLANA)','OD PIURA','SULLANA','OD PIURA',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA PUNO (PUNO)','OD PUNO','PUNO','OD PUNO',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA SAN MARTIN (TARAPOTO)','OD SAN MARTIN','TARAPOTO','OD SAN MARTIN',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA TACNA (TACNA)','OD TACNA','TACNA','OD TACNA',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA TUMBES (TUMBES)','OD TUMBES','TUMBES','OD TUMBES',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE DISCIPLINA UCAYALI (PUCALLPA)','OD UCAYALI','PUCALLPA','OD UCAYALI',3,2,25,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA Nº 01 - LIMA CALLAO (ARAMBURU)','ID Nº 01 - LIMA CALLAO','ARAMBURU','ID Nº 01 - LIMA CALLAO',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA Nº 02 - LIMA CALLAO (ARAMBURU)','ID Nº 02 - LIMA CALLAO','ARAMBURU','ID Nº 02 - LIMA CALLAO',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA Nº 03 - LIMA CALLAO (ARAMBURU)','ID Nº 03 - LIMA CALLAO','ARAMBURU','ID Nº 03 - LIMA CALLAO',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA Nº 04 ASUNTOS ESPECIALES A NIVEL NACIONAL (ARAMBURU)','ID Nº 04 ASUNTOS ESPECIALES A NIVEL NACIONAL','ARAMBURU','ID Nº 04 ASUNTOS ESPECIALES A NIVEL NACIONAL',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA AMAZONAS (CHACHAPOYAS)','ID AMAZONAS','CHACHAPOYAS','ID AMAZONAS',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA ANCASH (HUARAZ)','ID ANCASH','HUARAZ','ID ANCASH',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA AREQUIPA (AREQUIPA)','ID AREQUIPA','AREQUIPA','ID AREQUIPA',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA AYACUCHO (HUAMANGA)','ID AYACUCHO','HUAMANGA','ID AYACUCHO',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA CAJAMARCA (CAJAMARCA)','ID CAJAMARCA','CAJAMARCA','ID CAJAMARCA',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA CUSCO (CUSCO)','ID CUSCO','CUSCO','ID CUSCO',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA HUANCAVELICA (HUANCAVELICA)','ID HUANCAVELICA','HUANCAVELICA','ID HUANCAVELICA',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA HUANUCO (HUANUCO)','ID HUANUCO','HUANUCO','ID HUANUCO',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA ICA (ICA)','ID ICA','ICA','ID ICA',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA JUNIN (HUANCAYO)','ID JUNIN','HUANCAYO','ID JUNIN',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA LA LIBERTAD (TRUJILLO)','ID LA LIBERTAD','TRUJILLO','ID LA LIBERTAD',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA LAMBAYEQUE (CHICLAYO)','ID LAMBAYEQUE','CHICLAYO','ID LAMBAYEQUE',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA LORETO (IQUITOS)','ID LORETO','IQUITOS','ID LORETO',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA MADRE DE DIOS (PUERTO MALDONADO)','ID MADRE DE DIOS','PUERTO MALDONADO','ID MADRE DE DIOS',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA PASCO (CERRO DE PASCO)','ID PASCO','CERRO DE PASCO','ID PASCO',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA PIURA (PIURA)','ID PIURA','PIURA','ID PIURA',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA PUNO (PUNO)','ID PUNO','PUNO','ID PUNO',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA SAN MARTIN (TARAPOTO)','ID SAN MARTIN','TARAPOTO','ID SAN MARTIN',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA TACNA (TACNA)','ID TACNA','TACNA','ID TACNA',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA TUMBES (TUMBES)','ID TUMBES','TUMBES','ID TUMBES',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA DESCENTRALIZADA UCAYALI (PUCALLPA)','ID UCAYALI','PUCALLPA','ID UCAYALI',3,3,26,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA MACRO REGIONAL Nº 01 ASUNTOS ESPECIALES (COMPLEJO ARAMBURU)','IMR Nº 01 ASUNTOS ESPECIALES','ARAMBURU','IMR Nº 01 ASUNTOS ESPECIALES',3,4,27,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA MACRO REGIONAL Nº 03 LIMA - CALLAO (COMPLEJO ARAMBURU)','IMR Nº 03 LIMA - CALLAO','ARAMBURU','IMR Nº 03 LIMA - CALLAO',3,4,27,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA MACRO REGIONAL PIURA (PIURA)','IMR PIURA','PIURA','IMR PIURA',3,4,27,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA MACRO REGIONAL LAMBAYEQUE (CHICLAYO)','IMR LAMBAYEQUE','CHICLAYO','IMR LAMBAYEQUE',3,4,27,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA MACRO REGIONAL LA LIBERTAD (TRUJILLO)','IMR LA LIBERTAD','TRUJILLO','IMR LA LIBERTAD',3,4,27,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA MACRO REGIONAL LORETO (IQUITOS)','IMR LORETO','IQUITOS','IMR LORETO',3,4,27,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA MACRO REGIONAL HUANUCO (HUANUCO)','IMR HUANUCO','HUANUCO','IMR HUANUCO',3,4,27,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA MACRO REGIONAL JUNIN (HUANCAYO)','IMR JUNIN','HUANCAYO','IMR JUNIN',3,4,27,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA MACRO REGIONAL CUSCO (CUSCO)','IMR CUSCO','CUSCO','IMR CUSCO',3,4,27,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA MACRO REGIONAL AYACUCHO (HUAMANGA)','IMR AYACUCHO','HUAMANGA','IMR AYACUCHO',3,4,27,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA MACRO REGIONAL AREQUIPA (AREQUIPA)','IMR AREQUIPA','AREQUIPA','IMR AREQUIPA',3,4,27,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA MACRO REGIONAL PUNO (PUNO)','IMR PUNO','PUNO','IMR PUNO',3,4,27,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA MACRO REGIONAL SAN MARTIN (TARAPOTO)','IMR SAN MARTIN','TARAPOTO','IMR SAN MARTIN',3,4,27,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA MACRO REGIONAL ANCASH (HUARAZ)','IMR ANCASH','HUARAZ','IMR ANCASH',3,4,27,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA MACRO REGIONAL UCAYALI (PUCALLPA)','IMR UCAYALI','PUCALLPA','IMR UCAYALI',3,4,27,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA MACRO REGIONAL TACNA (TACNA)','IMR TACNA','TACNA','IMR TACNA',3,4,27,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('INSPECTORIA MACRO REGIONAL MADRE DE DIOS (PUERTO MALDONADO)','IMR MADRE DE DIOS','PUERTO MALDONADO','IMR MADRE DE DIOS',3,4,27,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('UNIDAD DE ASESORIA JURIDICA','UNIASJUR','ARAMBURU','UNIASJUR',3,1,29,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('UNIDAD DE PLANEAMIENTO Y EDUCACION','UNPLEDU','ARAMBURU','UNPLEDU',3,1,29,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('OFICINA DE ADMINISTRACION','OFAD','ARAMBURU','OFAD',3,1,29,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('JEFATURA DE ORDENES','JEFORD','ARAMBURU','JEFORD',3,1,29,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('UNIDAD DE COMUNICACION E IMAGEN INSTITUCIONAL','UNICIMA','ARAMBURU','UNICIMA',3,1,29,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('UNIDAD DE TRAMITE DOCUMENTARIO','UTD','ARAMBURU','UTD',3,1,29,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('UNIDAD DE TECNOLOGIA DE LA INFORMACION Y COMUNICACIONES','UNITIC','ARAMBURU','UNITIC',3,1,29,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('UNIDAD DE EVALUACION Y FICALIZACION DEL RESULTADO DE LAS INSPECCIONES','UNIEFRI','ARAMBURU','UNIEFRI',3,1,29,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('AYUDANTIA','AYU','ARAMBURU','AYU',3,1,29,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE INSPECCIONES LIMA-CALLAO Nº 01 (ARAMBURU)','EI LIMA-CALLAO Nº 01','ARAMBURU','EI LIMA-CALLAO Nº 01',3,5,30,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE INSPECCIONES LIMA-CALLAO Nº 02 (ARAMBURU)','EI LIMA-CALLAO Nº 02','ARAMBURU','EI LIMA-CALLAO Nº 02',3,5,30,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE INSPECCIONES LIMA-CALLAO Nº 03 (ARAMBURU)','EI LIMA-CALLAO Nº 03','ARAMBURU','EI LIMA-CALLAO Nº 03',3,5,30,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE INSPECCIONES LIMA-CALLAO Nº 04 (ARAMBURU)','EI LIMA-CALLAO Nº 04','ARAMBURU','EI LIMA-CALLAO Nº 04',3,5,30,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE INSPECCIONES LIMA-CALLAO Nº 05 (DIRECCION DE AVIACION POLICIAL)','EI LIMA-CALLAO Nº 05','DIRECCION DE AVIACION POLICIAL','EI LIMA-CALLAO Nº 05',3,5,30,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE INSPECCIONES LIMA-CALLAO Nº 06 (DIRECCION DE BIENESTAR Y APOYO AL POLICIA)','EI LIMA-CALLAO Nº 06','DIRECCION DE BIENESTAR Y APOYO AL POLICIA','EI LIMA-CALLAO Nº 06',3,5,30,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE INSPECCIONES LIMA-CALLAO Nº 07 (DIRECCION DE SEGURIDAD INTEGRAL)','EI LIMA-CALLAO Nº 07','DIRECCION DE SEGURIDAD INTEGRAL','EI LIMA-CALLAO Nº 07',3,5,30,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE INSPECCIONES LIMA-CALLAO Nº 08 (DIRECCION DE RECURSOS HUMANOS)','EI LIMA-CALLAO Nº 08','DIRECCION DE RECURSOS HUMANOS','EI LIMA-CALLAO Nº 08',3,5,30,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE INSPECCIONES LIMA-CALLAO Nº 09 (DIVISION DE PROTECCION DE CARRETERAS)','EI LIMA-CALLAO Nº 09','DIVISION DE PROTECCION DE CARRETERAS','EI LIMA-CALLAO Nº 09',3,5,30,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE INSPECCIONES LIMA-CALLAO Nº 10 (EESTP PTE.PIEDRA)','EI LIMA-CALLAO Nº 10','EESTP PTE.PIEDRA','EI LIMA-CALLAO Nº 10',3,5,30,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE INSPECCIONES LIMA-CALLAO Nº 11 (CALLAO)','EI LIMA-CALLAO Nº 11','CALLAO','EI LIMA-CALLAO Nº 11',3,5,30,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE INSPECCIONES LIMA-CALLAO Nº 12 (DIRECCION DE OPERACIONES ESPECIALES)','EI LIMA-CALLAO Nº 12','DIRECCION DE OPERACIONES ESPECIALES','EI LIMA-CALLAO Nº 12',3,5,30,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO ESPECIAL DE INSPECCIONES A NIVEL NACIONAL Nº 01 (ARAMBURU)','EEIANN Nº 01','ARAMBURU','EEIANN Nº 01',3,5,30,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO ESPECIAL DE INSPECCIONES A NIVEL NACIONAL Nº 02 (COMPLEJO HOSPITALARIO PNP LUIS N. SAENZ)','EEIANN Nº 02','COMPLEJO HOSPITALARIO PNP LUIS N. SAENZ','EEIANN Nº 02',3,5,30,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO ESPECIAL DE INSPECCIONES A NIVEL NACIONAL Nº 03 (DIRECCION DE ADMINISTRACION)','EEIANN Nº 03','DIRECCION DE ADMINISTRACION','EEIANN Nº 03',3,5,30,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('DEPARTAMENTO DE EVALUACION DE INSPECCIONES Y DE COORDINACION A NIVEL NACIONAL','DEICNN','ARAMBURU','DEICNN',3,1,30,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPOS DE CONTROL Y SUPERVISION DE SERVICIOS POLICIALES LIMA-CALLAO','ECSSP LIMA-CALLAO','ARAMBURU','ECSSP LIMA-CALLAO',3,6,31,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE CONTROL Y SUPERVISION DE SERVICIOS POLICIALES LIMA-CALLAO Nº 01','ECSSP LIMA-CALLAO Nº 01','ARAMBURU','ECSSP LIMA-CALLAO Nº 01',3,6,31,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE CONTROL Y SUPERVISION DE SERVICIOS POLICIALES LIMA-CALLAO Nº 02','ECSSP LIMA-CALLAO Nº 02','ARAMBURU','ECSSP LIMA-CALLAO Nº 02',3,6,31,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE CONTROL Y SUPERVISION DE SERVICIOS POLICIALES LIMA-CALLAO Nº 03','ECSSP LIMA-CALLAO Nº 03','ARAMBURU','ECSSP LIMA-CALLAO Nº 03',3,6,31,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE CONTROL Y SUPERVISION DE SERVICIOS POLICIALES LIMA-CALLAO Nº 04','ECSSP LIMA-CALLAO Nº 04','ARAMBURU','ECSSP LIMA-CALLAO Nº 04',3,6,31,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE CONTROL Y SUPERVISION DE SERVICIOS POLICIALES LIMA-CALLAO Nº 05','ECSSP LIMA-CALLAO Nº 05','ARAMBURU','ECSSP LIMA-CALLAO Nº 05',3,6,31,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE CONTROL Y SUPERVISION DE SERVICIOS POLICIALES LIMA-CALLAO Nº 06','ECSSP LIMA-CALLAO Nº 06','ARAMBURU','ECSSP LIMA-CALLAO Nº 06',3,6,31,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE CONTROL Y SUPERVISION DE SERVICIOS POLICIALES LIMA-CALLAO Nº 07','ECSSP LIMA-CALLAO Nº 07','ARAMBURU','ECSSP LIMA-CALLAO Nº 07',3,6,31,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE CONTROL Y SUPERVISION DE SERVICIOS POLICIALES LIMA-CALLAO Nº 08','ECSSP LIMA-CALLAO Nº 08','ARAMBURU','ECSSP LIMA-CALLAO Nº 08',3,6,31,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE CONTROL Y SUPERVISION DE SERVICIOS POLICIALES LIMA-CALLAO Nº 09','ECSSP LIMA-CALLAO Nº 09','ARAMBURU','ECSSP LIMA-CALLAO Nº 09',3,6,31,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('EQUIPO DE CONTROL Y SUPERVISION DE SERVICIOS POLICIALES LIMA-CALLAO Nº 10','ECSSP LIMA-CALLAO Nº 10','ARAMBURU','ECSSP LIMA-CALLAO Nº 10',3,6,31,0,1);
INSERT INTO unidadinspectoria (nombre,abrev,sede,siglas,orden,tipounidadinspectoria_id,unidadinspectoria_id,clasificacion,unidadfinal) VALUES ('DEPARTAMENTO DE EVALUACION, COORDINACION Y MONITOREO DE DISPOSICIONES DE COMANDO','DEICNN','ARAMBURU','DEICNN',3,1,31,0,1);

INSERT INTO usuarioperfil (cip,usuario_id,persona_id,unidadinspectoria_id,cargo_id,enabled_at,disabled_at,enabled) VALUES ('00391305',1,1,8,1,'11/05/2020',NULL,1);